package life.majiang.community.model;

public class Navurl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navurl.id
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navurl.url
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navurl.decription
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    private String decription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navurl.sort_number
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    private Integer sortNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navurl.top_id
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    private Integer topId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navurl.id
     *
     * @return the value of navurl.id
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navurl.id
     *
     * @param id the value for navurl.id
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navurl.url
     *
     * @return the value of navurl.url
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navurl.url
     *
     * @param url the value for navurl.url
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navurl.decription
     *
     * @return the value of navurl.decription
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    public String getDecription() {
        return decription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navurl.decription
     *
     * @param decription the value for navurl.decription
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    public void setDecription(String decription) {
        this.decription = decription == null ? null : decription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navurl.sort_number
     *
     * @return the value of navurl.sort_number
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    public Integer getSortNumber() {
        return sortNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navurl.sort_number
     *
     * @param sortNumber the value for navurl.sort_number
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    public void setSortNumber(Integer sortNumber) {
        this.sortNumber = sortNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navurl.top_id
     *
     * @return the value of navurl.top_id
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    public Integer getTopId() {
        return topId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navurl.top_id
     *
     * @param topId the value for navurl.top_id
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    public void setTopId(Integer topId) {
        this.topId = topId;
    }
}