package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.Navurl;
import life.majiang.community.model.NavurlExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NavurlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navurl
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    long countByExample(NavurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navurl
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    int deleteByExample(NavurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navurl
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navurl
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    int insert(Navurl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navurl
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    int insertSelective(Navurl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navurl
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    List<Navurl> selectByExampleWithRowbounds(NavurlExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navurl
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    List<Navurl> selectByExample(NavurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navurl
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    Navurl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navurl
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") Navurl record, @Param("example") NavurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navurl
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    int updateByExample(@Param("record") Navurl record, @Param("example") NavurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navurl
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    int updateByPrimaryKeySelective(Navurl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navurl
     *
     * @mbg.generated Tue Apr 28 15:12:41 CST 2020
     */
    int updateByPrimaryKey(Navurl record);
}